# -*- coding: utf-8 -*-
#
# codimension - graphics python two-way code editor and analyzer
# Copyright (C) 2010-2016  Sergey Satskiy sergey.satskiy@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""All the imports from the QT libraries"""

from PyQt5.QtCore import (
    QAbstractItemModel,
    QDir,
    QEvent,
    QEventLoop,
    QItemSelectionModel,
    QModelIndex,
    QObject,
    QRect,
    QRegExp,
    QSize,
    QSortFilterProxyModel,
    QStringListModel,
    Qt,
    QTimer,
    QUrl,
    pyqtSignal,
)
from PyQt5.QtGui import (
    QBrush,
    QColor,
    QCursor,
    QDesktopServices,
    QDoubleValidator,
    QFontMetrics,
    QIcon,
    QImage,
    QIntValidator,
    QKeySequence,
    QPainter,
    QPalette,
    QPixmap,
    QTextCursor,
)
from PyQt5.QtPrintSupport import QPrintDialog
from PyQt5.QtWidgets import (
    QAbstractItemView,
    QAction,
    QActionGroup,
    QApplication,
    QBoxLayout,
    QCheckBox,
    QColorDialog,
    QComboBox,
    QCompleter,
    QDialog,
    QDialogButtonBox,
    QDirModel,  # obsolete but used by completers
    QFileDialog,
    QFontDialog,
    QFrame,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QItemDelegate,
    QLabel,
    QLineEdit,
    QListView,
    QListWidget,
    QMainWindow,
    QMenu,
    QMenuBar,
    QMessageBox,
    QPlainTextEdit,
    QPushButton,
    QRadioButton,
    QScrollArea,
    QShortcut,
    QSizePolicy,
    QSplashScreen,
    QSplitter,
    QStackedWidget,
    QStyle,
    QStyledItemDelegate,
    QStyleFactory,
    QStyleOptionFrame,
    QStyleOptionViewItem,
    QTabBar,
    QTabWidget,
    QTextBrowser,
    QTextEdit,
    QToolBar,
    QToolButton,
    QToolTip,
    QTreeView,
    QTreeWidget,
    QTreeWidgetItem,
    QVBoxLayout,
    QWidget,
)

__all__ = [
    'QAbstractItemModel',
    'QAbstractItemView',
    'QAction',
    'QActionGroup',
    'QApplication',
    'QBoxLayout',
    'QBrush',
    'QCheckBox',
    'QColor',
    'QColorDialog',
    'QComboBox',
    'QCompleter',
    'QCursor',
    'QDesktopServices',
    'QDialog',
    'QDialogButtonBox',
    'QDir',
    'QDirModel',
    'QDoubleValidator',
    'QEvent',
    'QEventLoop',
    'QFileDialog',
    'QFontDialog',
    'QFontMetrics',
    'QFrame',
    'QGridLayout',
    'QGroupBox',
    'QHeaderView',
    'QHBoxLayout',
    'QIcon',
    'QImage',
    'QIntValidator',
    'QItemDelegate',
    'QItemSelectionModel',
    'QKeySequence',
    'QLabel',
    'QLineEdit',
    'QListWidget',
    'QListView',
    'QMainWindow',
    'QMenu',
    'QMenuBar',
    'QMessageBox',
    'QModelIndex',
    'QObject',
    'QPainter',
    'QPalette',
    'QPlainTextEdit',
    'QPixmap',
    'QPrintDialog',
    'QPushButton',
    'QRadioButton',
    'QRect',
    'QRegExp',
    'QScrollArea',
    'QShortcut',
    'QSize',
    'QSizePolicy',
    'QSortFilterProxyModel',
    'QSplashScreen',
    'QSplitter',
    'QStackedWidget',
    'QStringListModel',
    'QStyle',
    'QStyleFactory',
    'QStyledItemDelegate',
    'QStyleOptionFrame',
    'QStyleOptionViewItem',
    'QTabBar',
    'QTabWidget',
    'QTextBrowser',
    'QTextCursor',
    'QTextEdit',
    'QTimer',
    'QToolBar',
    'QToolButton',
    'QToolTip',
    'QTreeView',
    'QTreeWidget',
    'QTreeWidgetItem',
    'QUrl',
    'QVBoxLayout',
    'QWidget',
    'Qt',
    'pyqtSignal',
]
